GMOD/jbrowse

- src/JBrowse/View/Track/WiggleBase.js
This fixes the problem when using binary 0/1 tracks, zeros were not being displayed.
> Wiggle tracks now shows pixel values of 0 on mouse over

- src/JBrowse/View/Track/WiggleBase.js
The design is that when Log scale is toggled on, the mouse over pixel values still display the original value.
> Added a Log scale toggle to the Wiggle track menu

- src/JBrowse/Browser.js
- src/JBrowse/View/Track/HTMLFeatures.js
This adds the ability to show or hide track labels with a checkbox
We had added this feature to WebApollo 1.x awhile back, but I felt this functionality can also be backported to JBrowse core
I'm not sure if this affects the HideTrackLabels plugin but I thought that having it as a simple menu item can help users too
> Add a View menu item for Show/hide track labels

- css/sequence.css
- src/JBrowse/CodonTable.js
- src/JBrowse/View/Track/Sequence.js
Originally only `M`s were highlighted, instead of highlighting things which are actually starts. E.g. `TTG`, even though it is a recognised start codon in table 1, translates to L by default. The built in highlighter was not aware of the distinction and thus didn't highlight it as a possible start codon.
Configuration options are supplied to allow users to override this setting, just like they can with the `codonTable` setting. 
Here I have set `"codonStarts": ["AAA"],` in my `trackList.json` file:
> Allow overriding start/stop characters for highlighting in refseq track

- src/JBrowse/View/Track/_ExportMixin.js
We saw a scenario where one of our track types had a quirk with "Save track data" and I thought that it would be useful to have the ability to specify a custom exporter class.
This PR simply checks whether the name of the class that is specified by the track type contains slashes, and if it does, then we assume it is a full path to a exporter module rather than something that already exists in JBrowse namespace.
For example, I could have a class like this that inherits from the default gff3 exporter
```
define([
"dojo/_base/declare",
"JBrowse/View/Export/GFF3"
],
function(
declare,
ExportGFF3
) {
return declare(ExportGFF3, {
constructor: function() {
console.log("Initialized");
},
writeFeature: function(feature) { /* do custom exporter things... */ }
});
});
```
And then use it for some …
> Allow specifying custom exporter classes outside the JBrowse namespace

- src/JBrowse/Store/SeqFeature/SPARQL.js
Sometimes data providers reject the CORS preflight request, so this adds an option for disabling that, in particular for SPARQL data stores
This dojo FAQ page discusses the technique https://www.sitepen.com/blog/2014/01/15/faq-cors-with-dojo/
The Apollo hackathon uncovered that this patch was needed for a wikidata query
Ideally the data provider i.e. wikidata would accept the CORS request out of the box, but this seems like a needed workaround
> Add option to disable pre-flight request for SPARQL store

- src/JBrowse/Store/SeqFeature/GlobalStatsEstimationMixin.js
In some data stores, auto-calculation of statistics can be super slow.  Added a timeout so that JBrowse will not try for too long to try to estimate a store's global statistics.
> add a timeout to store stats calculations

- plugins/NeatCanvasFeatures/js/main.js
- plugins/NeatHTMLFeatures/js/main.js
**htmlfeatures**
**canvas**
As per request via @selewis 
I removed the configuration option, which seemed to remove everything instead of just the gradient.  
If there is a reason to have the gradient in there, I will figure out a way to make it optional, but I can't think of one.
> removed linear gradients

- src/JBrowse/Store/SeqFeature.js
- src/JBrowse/Store/SeqFeature/BAM.js
- src/JBrowse/Store/SeqFeature/BigWig.js
- src/JBrowse/Store/SeqFeature/GlobalStatsEstimationMixin.js
- src/JBrowse/Store/SeqFeature/VCFTabix.js
The stats estimation was given a timeout in #663 which is super, but it is also strict 500ms which leads to odd behavior such as that described in #727 
This PR adds two things
1) Configurable timeouts via a "storeTimeout" config variable. This timeout can be provided for a given track in their config, similar to how chunkSizeLimit can be modified in the config. The default for BAM, VCF, and BigWig is 3seconds. BigWig I think is important since autoscale global requires the global stats estimator to finish. The BAM is important since it causes behavior like #727 when it times out. Default for others is 500ms.
2) Handling the chunkSizeLimit error explicitly during stats estimation by replying with the same response as a timeout (i.e. just provide no statistics) which should fix #540 corner …
> Add configurable timeout and handle the dataoverflow error during stats estimation

- src/JBrowse/Browser.js
The alignment of the menubar buttons looks like it can be fixed by changing the text-align CSS property
It looks ok with both locationBar = separate and default
> Fix alignment of buttons for #680

- bower.json
Chrome 51 has some behavior that creates an error that says "normal is not defined" on page load
This can prevent jbrowse from loading altogether
The root of the problem is described here https://github.com/kriszyp/xstyle/issues/56
We can fix by bumping xstyle version from 0.3.1->0.3.2
> Fix 'normal is not defined' error on Chrome 51

- plugins/HideTrackLabels/js/main.js
This fixes the HideTrackLabels plugin to not re-show the track labels during scrolling
Follow up to comments made on this commit https://github.com/GMOD/jbrowse/commit/d4008c058854fb584edef9f344ca1a10599a876d
> Make the track labels not re-appear on scrolling

- index.html
Since the partial work done in CommentsTrack plugin was removed from the repo to avoid the travis ci build fail, the main stylesheet needed by the Comments Track was added to the index.html file manually.
> Load comments track main stylesheet from index view

- src/JBrowse/Browser.js
- src/JBrowse/Store/Hash.js
Hi!
This is a fix for the error message 'Error reading from name store' I get when opening a JBrowse instance for the first time, or clicking on "Go" with random stuff in the search box.
I'm not sure if this is very elegant, or if it could have some side effect, but I thought it was worth opening the PR.
> Fix for 'Error reading from name store'

- src/JBrowse/Browser.js
In some cases in  Apollo this variable was already an array causing breakages when the code called split. This *should* fix this issue.
This should not have a negative effect on the code otherwise.
Apologies for the unrelated deletions of trailing whitespace. I can re-commit without those if need be.
> Potential fix for gmod/apollo#1498

- src/JBrowse/Store/SeqFeature/_MismatchesMixin.js
The "advent" of long reads is upon us.... and you can try out open datasets like https://github.com/nickloman/massive-nanopore-silliness !
The fasta file NC_000913.fna and bam file gt350kb.split.sorted.bam are pretty good test files in that repo.
If added to jbrowse, an alignments2 track for example will work, but it is slow to scroll around. That seems to be because the mismatches are recalculated every time the read is rendered (and of course, mismatches are numerous over 50kb of read length), so this PR adds the ability to "cache" the mismatches on the feature object and this makes scrolling around faster.
> Add cacheMismatches option which greatly speeds up long reads processing

- src/JBrowse/View/Track/_FeatureDetailMixin.js
This adds a config variable subfeatureDetailLevel that can be set to limit to number of layers of subfeatures that get rendered
Level 0,1 includes only top-level (gene)
Level 2 includes two levels, e.g. top level and one sublevel (gene+transcript)
Level 3 includes three levels e.g. top level and two sublevels (gene+transcript+exon/cds), etc
Then it makes a button to load the subfeatures if this config option is enabled
Might help with https://github.com/GMOD/jbrowse/issues/559
> Add config to limit view details subfeatures

- index.html
- src/JBrowse/Browser.js
This PR makes available a new URL parameter named `fullviewlink`, used to control the visibility of the "Full-screen view" button/link.
This is potentially useful in situations where other parameters like `nav`, `overview`, `tracklist` are toggled _off_ (0) to generate an embeddable JBrowse view without any controls, suitable for taking screenshots.
Here is a working example instance on Araport.org, which shows this functionality: https://www.araport.org/locus/AT4G11330/browse?nav=0&overview=0&tracklist=0&fullviewlink=0
CC @keiranmraine
> Adds `fullviewlink` URL param to enable/disable "Full-screen view" link

- css/main.css
- src/JBrowse/Browser.js
This allows storing a list of plugins in the About box. The list will scroll also if there are a ton of plugins.
It lists the name of the plugin, and can also add author and url if the plugin adds the "author" and "url" properties to it's main object (e.g. this.url = 'blah', this.author='blah' in plugin constructor)
xref https://github.com/GMOD/jbrowse/issues/768
> Add list of plugins

- src/JBrowse/View/Track/Wiggle/XYPlot.js
As discussed in https://github.com/GMOD/jbrowse/issues/740
Adds 'noFill' option which results in just the top (or bottom) end of bar being rendered for XYplot.  Image shows 2 tracks, positive and negative values respectively (a mirror image of each other). 
Just need to add `"noFill": true` to track config, e.g. a base loaded BigWig track would now be:
```
{
"maxExportSpan": 500000,
"autoscale": "local",
"logScaleOption": true,
"style": {
"pos_color": "blue",
"neg_color": "red",
"origin_color": "#888",
"variance_band_color": "rgba(0,0,0,0.3)",
"height": 100
},
"label": "BigWig_1kb_1",
"key": "BigWig 1kb",
"type": "JBrowse/View/Track/Wiggle/XYPlot",
"category": "Local tracks",
"metadata": {},
"noFill": true
}
```
> XYPlot  - noFill option to give scatter like plots

- plugins/HideTrackLabels/js/main.js
Addresses #868 request, but requires that the hidetracklabels plugin is enabled.
> Add ability to set show_tracklabels=0 in config or &tracklabels=0 in url

- src/JBrowse/Browser.js
If you have in jbrowse.conf something like
[plugins.DebugEvents]
location = plugins/DebugEvents
And in trackList.json
"plugins": ["NeatCanvasFeatures"]
Then this causes an error because one is the simple "name" type and the other has the "location" type. This is a simple fix for that
> Allow flexible parsing of the list of plugin types

- src/JBrowse/View/FeatureGlyph/ProcessedTranscript.js
Assumes that JSON data for any particular gene feature being processed by JBrowse contains one complete CDS instead of disjointed features. The code in this PR makes use of the exon coordinates and total CDS span to infer the CDS parts.
Set `"inferCdsParts": true` in the track config to invoke this functionality.
This PR is being added to satisfy a specific use case, where JBrowse-compatible JSON data produced by the InterMine JBrowse REST API represents the CDS feature as a single element, mainly because of the way in which CDSs are loaded into the warehouse.
JBrowse installed at jbrowse.org without this fix: https://jbrowse.org/code/latest-release/?data=https://apps.araport.org/thalemine/service/jbrowse/config/3702&loc=Chr1:22311..32037&tracks=ThaleMine-3702-Gene&tracklist=0&nav=0&overvi …
> Adds config option `inferCdsParts` to ProcessedTranscript glyph

- src/JBrowse/Browser.js
In rare cases, it looks like the searchNames function can be called before loadNames is complete. 
This could have been exaggerated by making loadNames after initPlugins (#732), but conceivably it could have even happened in previous versions of jbrowse too
This PR just makes loadNames milestone a pre-requisite for searchNames
> Make sure loadNames has passed before performing searchNames

- build/Makefile
This changes the build slightly to use -fdx instead of -fd during release build
Note that it already used to do -fdx for makefile `superclean` target but after bower was implemented it switched to -fd with --excludes, but I think it's valid to change to -fdx with excludes
The effect of not having -fdx was visible in the 1.12.3rc1 where, for example, node_modules and extlib folders were included, when they can be omitted
> Make superclean use -fdx to delete node_modules, extlib, etc

- src/JBrowse/Browser.js
@enuggetry here's a little pull request to address comments on https://github.com/GMOD/jbrowse/commit/c7ba95e3b0d4038a3eb5e29505f0f3ffa643fd57
The summary being that sometimes the browser would crash if the xhr was too slow and browserMeta got called before it completed
> Use dojo/text instead of xhr to grab module info

- setup.sh
I think the check_bower command should be removed when jbrowse is pre-compiled (as in the 1.12.3 release) because otherwise it prints a ton of warnings and permission denied errors )ref #873).
I think the message about "reinstalling" dependencies is probably unneeded too, it doesn't seem like something I'd recommend a user do
> Update so that setup.sh does not try to run bower when pre-compiled

- src/JBrowse/Browser.js
- src/JBrowse/Store/NCList.js
- src/JBrowse/Store/NCList_v0.js
- src/JBrowse/Store/SeqFeature/NCList.js
This follows up on this PR https://github.com/GMOD/jbrowse/pull/839 to allow more cross-origin support. Example
http://jbrowse.org/code/JBrowse-1.12.3/?data=https%3A%2F%2Fcdn.rawgit.com%2Fgmod%2Fjbrowse-registry%2F227c645c%2Fdemos%2Fgwasviewer&loc=16%3A36137482..54208432&tracks=&highlight=
This link currently doesn't work but would succeed after this applying this change (can try out the same url locally on your computer)
> Disable CORS header on refSeqs.json request

- .bowerrc
- bower.json
This is a PR follow up to #906 to restore bower config files
It was mentioned that bower can still be useful in installing dependencies in test datasets
In the plugin context it was sort of interesting because it could fit into a workflow that included jbrowse as a "package" see http://searchvoidstar.tumblr.com/post/143063018578/creating-a-testing-framework-for-jbrowse-plugins
In #906 it was mentioned that the npm doesn't yet have the ability to install itself as a package so retaining bower until this is done could be useful
> Add bower config files back

- src/JBrowse/View/Track/Alignments.js
- src/JBrowse/View/Track/Alignments2.js
- src/JBrowse/View/Track/_AlignmentsMixin.js
@enuggetry @nathandunn @cmdcolin 
There was a request for adding the ability to hide unspliced reads while viewing RNAseq alignment BAMs. 
This PR aims at providing an option to hide reads that are not spliced, inferred from the cigar string of a read.
> Add option to hide unspliced reads for BAM tracks

- src/JBrowse/Store/SeqFeature/BAM.js
Currently the _getFeatures function in JBrowse/Store/SeqFeature/BAM uses `this.refSeq.name` to get the sequence name instead of getting the sequence name from the `query` argument.
While this works for JBrowse, it can be difficult if the `query` contains a sequence name which is different from `this.refSeq.name`.
This PR aims at fixing this minor detail.
@nathandunn @enuggetry
> A minor fix for _getFeatures in BAM store

- .travis.yml
- release-notes.txt
- src/JBrowse/GenomeView.js
- src/JBrowse/View/Track/BlockBased.js
Add config feature to move track labels/menus above the features so as not to obscure the features. Adds a little more spacing between tracks and between the first track and the genome view. Activated with trackLabels: "no-block" in trackList.json.
> Add config option - no obscure track labels

- setup.sh
This PR is to address the issue observed in https://github.com/GMOD/Apollo/issues/1820
While running `setup.sh`, the `biodb-to-json.pl` step keeps running indefinitely while it generates large temp files to the point of filling all available disk space.
The behavior is observed only on **MacOS High Sierra**. 
This PR modifies `setup.sh` to check if the system is on MacOS High Sierra and skip running `biodb-to-json.pl` if it is.
@nathandunn @enuggetry
> In setup.sh, add check to suppress running biodb-to-json.pl if system is on MacOS High Sierra

- bin/prepare-refseqs.pl
- src/perl5/Bio/JBrowse/Cmd/FormatSequences.pm
Just like `bin/flatfile-to-json.pl`, this change enables a `--config` flag on `prepare-refseqs.pl` which allows adding arbitrary JSON to the refseq when it is added.
This is needed because I've started adding the `metadata` blocks for faceted track selector and as part of a completely automated pipeline. My tool that's building the trackList.json needs to be adding metadata to the right reference sequence, and I don't want to have to look through and guess which refseq track it is supposed to be.
> Allow adding arbitrary config to refseq block

- src/JBrowse/GenomeView.js
I think one of the code changes for issue #901 might have intended to use the config variable trackPadding in this way, so this is just a one line PR
Can see in screenshots
Before (has small amount of tracklabel overhanging previous track):
After:
> Make the trackPadding attribute use config for issue #901

- src/JBrowse/View/Track/_FeatureDetailMixin.js
I believe this is what was intended. Before this commit, all of .additional's children (other than the h2) were at the same level. This PR moves them into the container.
> Fixes hierarchy of additional relative to core

- src/JBrowse/Browser.js
cmdcolin's suggested () addition to fix the test for defaultTracks in config as an array. fixes #892
> fix for v1.12.3 defaultTracks

- bin/add-bam-track.pl
- tests/selenium_tests/yeast_biodb_test.py
Useful for automatisation in the case where we want to add a lot of BAM files with summary histograms from quantitrative data (bigwig files).
> Add histograms argument to the script add-bam-track.pl

- tests/js_tests/spec/BAM.spec.js
There was an error with properly initializing the BAM tests in jasmine that wanted to have the FeatureFiltererMixin enabled. Fixed by adding these to the configs that are initialized in the tests. Ref #994
> Fix error about filter mixin

- utils/jb_run.js
- utils/jb_setup.js
Currently if you do a "npm install @gmod/jbrowse" you get main jbrowse code in "node_modules/@gmod/jbrowse"
This fixes some of the accessory scripts to support this. I'm not sure if all node js versions install node_modules paths this way, but I tested v9 and v6
Also, AFAIK, the `npm install jbrowse` didn't install, it needed @gmod/jbrowse, hence this issue
> NPM module is located at @gmod/jbrowse

- css/track_styles.css
https://github.com/GMOD/jbrowse/issues/605
For me and multiple users, seeing highly transparent (low opacity) very light grey bars against a light background is not good use of contrast.
I have made colours darker and increased opacity to mitigate this and make objects more visible, which enhances usability.
> colours: increase contrast

- release-notes.txt
- src/JBrowse/Browser.js
call `Browser.navigateTo` when an item is clicked in the location search dropdown menu, to just go to that item immediately
fixes #616 
just merge if it looks fine
> go to search completion immediately on click

- src/JBrowse/View/Track/SNPCoverage.js
Exposed 2 parameters to the user via the config file. They set the
minimum proportion (`indicatorProp`) and minimum depth
(`indicatorDepth`) of alternative alleles required to render the
SNP indicator below a SNPCoverage track.
Default values are chosen so that indicators are displayed (almost)
as they would have been before this commit. The only difference is
that now SNP indicators will also display if the alternative alleles
are exactly half the total coverage at a site. This is due to a change
in a conditional from ">" to ">=".
> SNPCoverage: Exposed params for user customisation

- index.html
- release-notes.txt
This PR adds a basic "loading screen" while the browser is waiting to be initialized. Then, after the loadRefSeqs milestone is passed, the text is removed. This helps with slow connections and large refSeqs.json files
This was documented as a customization that users can make to index.html in the configuration guide, but it seems like it could be useful to have it by default? http://gmod.org/wiki/JBrowse_Configuration_Guide#Configure_a_Loading_Page
> Add "loading screen"

- css/main.css
- release-notes.txt
- src/JBrowse/View/Track/BlockBased.js
- src/JBrowse/View/Track/_FeatureDetailMixin.js
This is a follow-on to #861, whic makes the feature detail popup only render one layer of subfeatures by default.
Since there is a 'Show subfeatures' button, this new default probably won't have any ill effects.  And it should prevent most problems like the one in #559, in which the feature detail popup for a gene with a great many alternative transcripts (for several hundred features in total) takes upwards of 30 seconds to render all of the subfeature details, blocking the main UI thread all the while.
> make subfeaturelevel default to 2

- build/Makefile
When the plugins that have been cloned from git are built by jbrowse the superclean target fails to delete the generated build folders like JBrowse-1.12.4-dev/plugins/BlahPlugin. Reason being, git clean doesn't like to delete git repositories. So, make sure to delete any .git folder from the generated plugin builds. Probably a reasonable thing to do anyways
> Delete git directory of built plugins

- docs/tutorial/conf_files/volvox.json
There is a error with the json in the volvox biodb config file that made the coloring on the track get ignored
This restores the color :)
> Fix volvox track coloring

- plugins/HideTrackLabels/js/main.js
This PR fixes #1017 by checking for existence of a button before setting dom attributes, and checking for the config show_tracklabels to hide nodes
> Fix hidetracklabels when nav is gone

- plugins/HideTrackLabels/js/main.js
This is a PR that addresses an issue from https://github.com/GMOD/jbrowse/pull/1018
Basically there was a spelling in error in getting the DOM node and then the logic for removing the hidden-titles was not using removeAttr
Sorry bout that! Should really try and reduce complexity of this at some point
> Fix hide track labels logic for toggling

- src/perl5/Bio/JBrowse/Cmd/IndexNames.pm
Modified according to the functions of vcf names indexing. Aim to fix the fourth bug in #780
> Add support to index names for gff tabix (#780)

- docs/tutorial/data_files/volvox.subsubparts.gff3.conf
This fixes #1029 by moving the closing bracket away from the first column of the config file
Potentially it would be cool if that wasn't required, but it is explained in the JBrowse config guides that this is necessary
> Fix error with callback

- setup.sh
I was seeing an error happening if I ran setup.sh twice in a row, it would give an error that the command webpack was not found:
```
$ ./setup.sh            
Gathering system information ...done.                                                                                                                                                                       
NOTE: Legacy scripts wig-to-json.pl and bam-to-json.pl have removed from setup. Their functionality has been superseded by add-bam-track.pl and add-bw-track.pl. If you require the old versions, please use
JBrowse 1.12.3 or earlier.                                                                                                                                                                                 
Installing node.js …
```
> Fix error with running setup.sh twice

- setup.sh
- yarn.lock
Using node 10 gives this error
node v10.0.0 found, but node version 6 or later must be installed.
Modifying the comparison for node_major_version seems to fix it (ref https://stackoverflow.com/questions/18668556/comparing-numbers-in-bash)
> Properly check for node version

- src/perl5/Bio/JBrowse/Cmd/IndexNames.pm
There is a pretty large memory leak in generate-names.pl referenced in #1058 
It is pretty clear by looking at a task manager when the memory usage is climbing, so I did a git bisect and just looked at the memory usage of perl each time running generate-names
It narrowed down to this commit https://github.com/GMOD/jbrowse/commit/e34ab06ccbd543a4ad9344440d91c0d5ae2f7af5
I think the specific hunk that is the culprit is this
```
return sub {
-        unless( @operation_buffer ) {
-            if( my $name_record = $record_stream->() ) {
-                #$self->{stats}{namerecs_converted_to_operations}++;
-                push @operation_buffer, $self->make_operations( $name_record );
-            }
+        while( @operation_buffer and my $name_record = $record_stream->() ) {
+ …
```
> Fix memory leak on generate-names.pl

- src/JBrowse/Model/ArrayRepr.js
- src/JBrowse/Model/SimpleFeature.js
- src/JBrowse/View/Track/WiggleBase.js
This is a PR that adds auto-lower-casing the feature.get('...') argument for NCList ArrayRepr features and SimpleFeature objects
This helps https://github.com/GMOD/jbrowse/issues/1068
I can't forsee any negative consequences because the attributes are already lowercased
> Auto lower case gff and nclist feature.get arguments

- src/JBrowse/Store/SeqFeature/GFF3Tabix.js
This adds a configurable "dontRedispatch" option that avoids very long GFF3Tabix fetches described in #1076
> Dont redispatch option

- setup.sh
We saw an issue when a user without NPM/node ran the setup.sh script that it would exit without giving a nice error message
I saw that this is likely due to `set -e` so this is disabled around this block. Additional version information is given in the error messages now also
> Fix setup.sh error checking for node/npm

- release-notes.md
- src/JBrowse/Model/CSIIndex.js
- src/JBrowse/Store/SeqFeature/BAM/File.js
The initial fetch for BAM was broken due to not referencing the indexes minAlignmentVO (virtual offset) correctly. This actually affected BAI indexed BAM files just due to how it was moved into a separate modules when the CSI indexing format was merged, but should be fixed now.
Thanks so much to @nathanhaigh  for doing some pre-release testing to catch this! Fixes #1097
> Fix initial fetch bam

- src/JBrowse/Store/SeqFeature/BAM.js
- src/JBrowse/Store/SeqFeature/BEDTabix.js
- src/JBrowse/Store/SeqFeature/GFF3Tabix.js
- src/JBrowse/Store/SeqFeature/VCFTabix.js
- src/JBrowse/View/FileDialog/ResourceList.js
- src/JBrowse/View/FileDialog/TrackList/BAMDriver.js
- src/JBrowse/View/FileDialog/TrackList/GFF3TabixDriver.js
- src/JBrowse/View/FileDialog/TrackList/VCFTabixDriver.js
- src/JBrowse/View/FileDialog/TrackList/_MultiIndexedFileDriver.js
- tests/js_tests/spec/AddFiles.spec.js
This is a method that enables BAM,VCFTabix,GFF3Tabix,BEDTabix to use the CSI index
I did not flesh out the finalizeConfiguration section of the loader because it had some complex logic. Nevertheless, the code stands up ok without it, and loads tracks with multiple index types (can do BAM+BAI, BAM+CSI, VCF+TBI, VCF+CSI, etc)
> Enable CSI indexes in the Track->Open dialog

- src/JBrowse/Browser.js
By perfoming a lookup of the ref seq name before performing `locstring` parsing, we can fix #1118.
> Do ref seq lookup before loc string parsing

- src/JBrowse/Store/SeqFeature/GFF3.js
- src/JBrowse/Store/SeqFeature/GFF3Tabix.js
This converts to use getFeatures for GFF3Tabix (since multiple isoforms of the same feature doesn't really increase feature density) and crucially adds a less-than-or-equal-to instead of just less-than in the histogram bin fill
> Use proper histogram calculation for GFF type stores

- src/JBrowse/Model/XHRBlob.js
- src/JBrowse/Store/RemoteBinaryFile.js
- src/JBrowse/Store/SeqFeature/BAM.js
- src/JBrowse/Store/SeqFeature/BEDTabix.js
- src/JBrowse/Store/SeqFeature/BigWig.js
- src/JBrowse/Store/SeqFeature/CRAM.js
- src/JBrowse/Store/SeqFeature/GFF3Tabix.js
- src/JBrowse/Store/SeqFeature/IndexedFasta.js
- src/JBrowse/Store/SeqFeature/TwoBit.js
- src/JBrowse/Store/SeqFeature/VCFTabix.js
- src/JBrowse/Store/SeqFeature/VCFTribble.js
- src/JBrowse/Store/TabixIndexedFile.js
This PR adds a concept called expectRanges to XHRBlob
It could be argued that this is more severe than a "loud warning" but if a server is doing HTTP 200 for a byte-range request it is very non-compliant
Ref #1132
> Add expectRanges to XHRBlob to ensure Range requests give 206 status

- src/JBrowse/ConfigManager.js
- tests/data/conf/dataRoot.json
- tests/js_tests/spec/ConfigManager.spec.js
This PR fixes #627 a bug that is basically that if dataRoot is configured in the config file it is ignored
It solves this in a couple ways
1) It does not fill templates in the initial config. the initial config templates basically only includes the "refSeqs" attribute that references {dataRoot} and the names which also references {dataRoot}. By deferring this, the dataRoot still gets resolved but to the right place after the config is parsed
2) It also avoids the issue of if dataRoot is in config, and &data= is supplied via url (which gets mapped to dataRoot) then it prioritizes the &data= URL
> Fix problem with dataRoot in config

- package.json
- src/JBrowse/Store/SeqFeature/CRAM.js
- src/JBrowse/View/Track/_AlignmentsMixin.js
- yarn.lock
> add seqs to cram features

- src/JBrowse/View/Track/BlockBased.js
Changes:
- use this.config.metadata if we can, trackMetaDataStore mangles the keys
- if trackSelector.renameFacets was defined, use the formatted keys provided
- instead of blanket ucFirst: only apply if all lowercase, and also swap underscores for spaces to show camel case nicer
- sort keys alphabetically (instead of current random order)
Why:
I'm setting up a fairly large and heterogeneous tracks display. An example URL on a perennial and unstable test site that nobody should rely on, but currently shows a vaguely correct picture is:
http://test.parasite.wormbase.org/jbrowse/index.html?data=%2Fjbrowse-data%2Fbursaphelenchus_xylophilus_prjea64437%2Fdata
I am aggregating data into faceted track displays. They work fantastically - I believe it is genuinely possible to use the display to …
> Improve keys formatting in "About this track"

- build/format_release_notes.pl
This PR does two things
1) Only formatting the release notes for the {{NEXT}} release
2) Checking for only "space" or "open paren" before a github username, specifically so NPM links to the @gmod organization like @gmod/jbrowse for example aren't broken.
These things combined could facilitate automatically creating a blogpost a little easier
> Fix parsing of the release notes markdown

- src/JBrowse/standalone.js
- webpack.config.js
This creates a standalone entry point where a user can manually initialize the Browser object for #1094 
Then you can create a minimal index.html with something like
```
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>JBrowse</title>
<script type="text/javascript">
window.onerror=function(msg){
if( document.body )
document.body.setAttribute("JSError",msg);
}
window.addEventListener('load', () => {
var JBrowse = new Browser({
containerID: 'GenomeBrowser',
dataRoot: 'sample_data/json/volvox'
})
});
</script>
<style>
html, body, div.jbrowse {
margin: 0;
padding: 0;
height: 100%;
width: 100%;
}
</style>
<script type="text/javascript" src="dist/browser.bundle.js" charset="utf-8"></script>
</head>
<body>
<div class="jbrowse" …
```
> Create standalone entrypoint for manual instantiation

- build/Makefile
The full release target was identified as unnecessary given that the full NPM+Webpack is run anyways on JBrowse dev releases. Therefore, users needing "dev" builds can simply download the "Source code" packages from the github releases or use an actual github clone
This PR removes the "full release" or the JBrowse-####-dev.zip file from release
> Remove full release

- src/JBrowse/Util.js
Added toString() because we faced an issue where str is not a string and replace() cannot be called while testing intermine integration
If you think this place is not a good place to put toString(), feel free to change it.
> Handled a case that str is not a string

- src/JBrowse/ConfigAdaptor/JB_json_v1.js
This PR enhances JBrowse's config to deduct the proper storeClass from urlTemplates given in a config file
This can make hand typing configs more minimal since you dont manually have to type out a storeClass
> Automatic storeClass track type deduction

- src/JBrowse/Model/XHRBlob.js
Resolves #1180 (I think)
Add failure callback since tenaciousFetch throws an error when the retries run out.
> Add failure callback to tenaciousFetch

- src/JBrowse/Store/SeqFeature/BED.js
- src/JBrowse/Store/SeqFeature/BEDTabix.js
- src/JBrowse/Store/SeqFeature/GFF3.js
- src/JBrowse/Store/SeqFeature/GFF3Tabix.js
- src/JBrowse/Store/SeqFeature/RegionStatsMixin.js
This is a PR to address part of #1192
This PR adds a function to track the "max score" on the store.maxScore property that is updated for the max over the region. This is because if this is not done, the stats.max value returned by getRegionFeatureDensity over a small region become smaller than the actual max over the view causing the histogram to set the Y scale to a small value when the actual data is larger
This also extracts the region stats into a mixin that can be applied to other store classes, so BED and BEDTabix are added here
> Add region stats mixin that has correction for max score

- src/JBrowse/View/Track/CanvasFeatures.js
This is a PR to address #1214 where the Y scale bar would be displayed over features. I think it is because the fillHistograms was async so it would be determined at some point to back out of showing histograms but the async would complete and show it (due to issues like #1190) 
This PR makes it explicit to not add the y-scale if it hits the async fillHistograms code after determining to not show them
> Add a static variable to check against adding the y-scale bar

- docs/site/mouse_configs.md
- src/JBrowse/View/Track/_FeatureDetailMixin.js
This PR simply adds a hideSequenceBox config variable. There is not any additional options for this config e.g. only hiding the subfeatures sequences since #1211 says that featuresequence plugin is delegated for all other sequence displaying
> Hide sequence box configuration

- docs/site/track_selectors.md
- jbrowse.conf
- src/JBrowse/View/TrackList/Hierarchical.js
- tests/js_tests/main.js
- tests/js_tests/spec/Hierarchical.spec.js
This adds a `categoryOrder` configuration option to the tracklist. This is just a comma separated list of category names
So, if applied to volvox sample, you can specify
categoryOrder = VCF, Transcripts, Miscellaneous
This will sort these categories to the top. Small amount of code reformatting goes along with this PR but the core is just the track sorting :)
> Add categoryOrder configuration

- .travis.yml
- setup.sh
- webpack.config.js
This PR makes running ./setup.sh use a production build. This can be turned off by setting an environment variable
JBROWSE_BUILD_MIN=0 ./setup.sh
But by default you still just run ./setup.sh which is automatically a production build
Notes:
- The time difference for setup.sh for me with node modules already downloaded is 30 seconds for JBROWSE_BUILD_MIN=0 vs 90 seconds for JBROWSE_BUILD_MIN=1 (with 1 being the new default by this PR)
- I also disabled UglifyJsPlugin parallel because it was causing hanging under WSL (possible xref https://github.com/jupyterlab/jupyterlab/issues/4276) but removing it didn't modify build times for me
The payload of the initial page load is about 877kb vs 1.8Mb
> Make setup.sh use webpack production build

- src/JBrowse/Store/SeqFeature/BigWig/RequestWorker.js
This is a PR to address #1226 which found a certain bigbed file that was not able to be loaded natively. I found that essentially a "Range" object was created where max less than the min, and then no action was taken in a specific for loop.
I found that I could modify a Range object creation to remove this particular "Math.min" operation to fix this issue. It's not exactly clear what purpose this had but removing it didn't seem to cause any issue on BigBed or BigWig files I tested. There is also no similar Math.min type operation in the dalliance codebase for BigWig from what I could tell
> Avoid issue where Range can have max less than min

- docs/site/embedding.md
- release-notes.md
- tests/iframeless-embed.html
- webpack.config.js
- website/deploy.sh
- website/sidebars.json
Adds some docs about iframe and iframeless embedding.  Also adds support for JBROWSE_PUBLIC_PATH, which I discovered was kind of needed to make docs that are satisfactory. ;-)
fixes #1213
> embedded mode docs

- build/dojo-loader-config.js
- build/glob-loader.js
- src/JBrowse/main.js
- webpack.config.js
Add `standalone.js` to the list of files that `glob-loader.js` looks for. Also includes a fix so JBrowse doesn't complain about not being able to find `empty.gif` when JBROWSE_PUBLIC_PATH is overridden.
Resolves #1238
> Fix for embedded minified builds

- docs/site/config_canvas_features.md
- src/JBrowse/View/FeatureGlyph/Gene.js
- src/JBrowse/View/FeatureGlyph/UnprocessedTranscript.js
- src/JBrowse/View/Track/CanvasFeatures.js
This adds an "unprocessed transcript" glyph with an `unprocessedTranscriptColor` config variable that distinguishes it from the other transcripts
This code uses the  `noncodingType` config (analogous to `transcriptType`) to render non-coding features with a gene parent correctly
This references #1106 although it's not a true pseudogene glyph, it handles unprocessed transcripts like ncRNA, lncRNA, miRNA, etc. Issues like #757 are potentially also relevant but was closed with a workaround
> Add unprocessed transcript glyph

- docs/site/embedding.md
- release-notes.md
- src/JBrowse/Browser.js
- src/JBrowse/main.js
This adds more information about embedding and adds a section on using `browser.bundle.js` to embed JBrowse with a custom runtime-generated config.
I updated some of the embedding examples to make sure they'll actually work when published to the site, since they depend on the JBrowse that is installed on the server. You can see this in action live on a beta page I put of this doc page on the website: https://jbrowse.org/docstest/embedding.html
A couple oddities:
* The loading screen div doesn't seem to get destroyed in the embedded div example
* Is there a way to keep it from adding all the information to the URL of the page?
> Add more embedding info to docs

- src/JBrowse/Browser.js
Complements genome bookmark feature (for datasets under the Genome menu).
if defined in config, the selected dataset will load into the parent of an iframe, instead of in the iframe.
e.g.:
```
"datasetLinkParent":true,
"datasets": {
"wheat": {
"name": "Wheat",
"url":"http://localhost/a.html",
},
"barley": {
"name": "Barley",
"url":"http://localhost/b.html",
}
}
```
> add datasetLinkToParent option 

- package.json
- src/JBrowse/Browser.js
- src/JBrowse/Model/VCFFeature.js
- src/JBrowse/Util.js
- src/JBrowse/View/DetailsMixin.js
- src/JBrowse/View/FeatureGlyph/Box.js
- src/JBrowse/View/Track/CanvasFeatures.js
- src/JBrowse/View/Track/Wiggle/XYPlot.js
- src/JBrowse/View/Track/_VariantDetailMixin.js
- tests/js_tests/spec/VCF.spec.js
- yarn.lock
Incorporates a new version of \@gmod/vcf which should speed up the initial load of a VCF that has a lot of samples.
@cmdcolin can you see if this branch speeds things up on your machine?
Volvox track with >1000 samples loads in <2s for me.
Resolves #1255
> Speed up VCF initial load

- src/perl5/Bio/JBrowse/FeatureStream/GFF3_LowLevel.pm
- tests/data/whitespace.gff3
- tests/perl_tests/flatfile-to-json.pl.t
- yarn.lock
This performs whitespace trimming on the attribute keys and values in a GFF3. Multivalued comma separated lists of things in the GFF3 attributes also individually get the start and end trimming.
> Fix whitespace in flatfile keys and values

- package.json
- src/JBrowse/Store/SeqFeature/GFF3Tabix.js
- tests/js_tests/spec/GFF3Tabix.spec.js
This addresses #1244 for GFF files. The crc32 of the line is assigned as the uniqueID in a similar way to the fileOffset that was there already
> Fix inconsistent layout on some GFF features

- src/JBrowse/Model/VCFFeature.js
- src/JBrowse/View/Track/_VariantDetailMixin.js
- tests/js_tests/spec/VCF.spec.js
If there are elements with no-call attributes with no supporting data, then it displays the genotype table somewhat weirdly
Before
After
The no-call data in volvox had supporting data for the no-calls so this wasn't detected there
Also, maybe it is not necessary to add the metadata to all VCF genotypes?
> Fixup genotype table for nocall

- docs/site/config_html_features.md
- docs/site/mouse_configs.md
- docs/tutorial/conf_files/volvox.json
- src/JBrowse/Model/VCFFeature.js
- src/JBrowse/Util.js
- src/JBrowse/View/DetailsMixin.js
- src/JBrowse/View/FeatureGlyph/Box.js
- src/JBrowse/View/Track/CanvasFeatures.js
- src/JBrowse/View/Track/HTMLFeatures.js
- src/JBrowse/View/Track/Wiggle/XYPlot.js
- src/JBrowse/View/Track/_AlignmentsMixin.js
- src/JBrowse/View/Track/_FeatureDetailMixin.js
- tests/js_tests/spec/VCF.spec.js
@garrettjstevens This is sort of a modification to to the escaping/unescaping approach that was going on.
If you want to test and give feedback let me know!
> Escape html places

- src/JBrowse/Store/SeqFeature/CRAM.js
Ref #1273 
This avoids the additional check for the refseq existing in the samHeader so that when it does not exist it doesn't try and do any fallbacks
> Add a fix for CRAM displaying on wrong chromosome

- package.json
- src/JBrowse/Browser.js
- webpack.config.js
- yarn.lock
I found this PR to dojo-webpack-plugin enabled webpack 4 builds to work with jbrowse https://github.com/OpenNTF/dojo-webpack-plugin/issues/185
There are not any urgent reasons to upgrade afaik. Purported speed improvements and better build defaults for dev vs prod builds but its not altogether a big thing for jbrowse codebase
> Webpack4 build

- src/JBrowse/Model/XHRBlob.js
This adds some changes to bypass http-range-fetcher basically when there are full file requests like for an index file, where in that case the range end is undefined and start is just 0
Addresses #1289 
Could also be addressed on the http-range-fetcher side of things but I basically saw it as unnecessary to divide into chunks so it is implemented with plain fetches here (with a small extra lru cache)
> No content range fixes

- docs/site/config_bigwig.md
- src/JBrowse/View/Ruler.js
- src/JBrowse/View/Track/Wiggle/XYPlot.js
This adds fixBounds config to XYPlot tracks which can be set to false, "none", "micro", "minor", or "major" (default major, setting to false == 'none')
Applies to both fixLower and fixUpper in https://dojotoolkit.org/reference-guide/1.10/dojox/charting.html
> Optional fix bounds on XYPlot ruler

- jbrowse.conf
- src/JBrowse/View/Track/HTMLFeatures.js
This PR allows to display gene subfeatures in HTMLFeatures (and NeatHTMLFeature) tracks, even if topLevelFeatures is not set "properly".
This is typically for gff files containing gene > mRNA > exon/CDS data.
Setting topLevelFeatures works nice, but : 
- people uploading gff files don't know about it, and they have no easy way to set it from the upload box (and in the end they complain about it to me)
- CanvasFeatures tracks are already able to display this kind of data with all the subfeatures
- this is such a typical gff structure that I would expect jbrowse to display it properly out of the box
The code is inspired/adapted from https://github.com/GMOD/jbrowse/pull/996
Without this patch:
With this patch:
> Display gene subfeatures even if topLevelFeatures is not set

- website/siteConfig.js
Redirects must be followed to download Github releases with curl. Otherwise, the downloaded object is the Github response informing about the redirect, not the released .zip file.
As of today, following the installation instructions downloads a text file containing only HTML:
```
20:22 $ curl -O https://github.com/GMOD/jbrowse/releases/download/1.16.3-release/JBrowse-1.16.3.zip
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   606    0   606    0     0   1037      0 --:--:-- --:--:-- --:--:--  1035
20:22 $ unzip JBrowse-1.16.3.zip 
Archive:  JBrowse-1.16.3.zip
End-of-central-directory signature not found.  Either this file is not
a zipfile, or it constitutes one disk of a multi-part archive.  In the
latter case …
```
> Add -L flag to curl in documentation

- src/JBrowse/View/Track/HTMLFeatures.js
Some things were missing in https://github.com/GMOD/jbrowse/pull/1340 as a gene>mrna>exon track is now displayed properly by default, but can't be dragged in Apollo.
The Apollo issue is there: https://github.com/GMOD/Apollo/issues/2099
This is still WIP I guess, can't test more today
> Fix getFeatDiv when inferHTMLSubfeatures is set

- package.json
- release-notes.md
- yarn.lock
This fixes some issues noted in tabix-js but is pending a resolution about the build where babel-runtime (6) and @babel/runtime (7) are getting into a weird state (ref https://github.com/OpenNTF/dojo-webpack-plugin/issues/211)
This PR is just better error handling essentially at the moment
> Better tabix error handling for longer genomes

- src/JBrowse/Browser.js
- src/JBrowse/Store/SeqFeature/CRAM.js
- src/JBrowse/Store/SeqFeature/IndexedFasta.js
- src/JBrowse/Store/SeqFeature/SequenceChunks.js
- src/JBrowse/Store/SeqFeature/TwoBit.js
- tests/js_tests/spec/RegularizeRefSeqs.spec.js
- tests/js_tests/spec/TwoBit.spec.js
Currently there are examples of CRAM name regularizing failing due to interaction with the sequence stores
* We have a CRAM using nomenclature `MT`
* The FASTA is using nomenclature `MT`
* The system internal to CRAM uses name regularization and makes this `chrm`
* Then it requests `chrm` from the seqFetch callback, at which point it fails
When it gets to the seq store, there is differing behavior depending on seqStore
1) The IndexedFasta does not use the query name, it uses this.refSeq.name, so it actually works
2) The SequenceChunks does something called compareReferenceSequence(this.refSeq.name, query.ref) and if this is 0, then it queries with this.refSeq.name. there was a bug with this that resulted in MT getting double regularized though so it went from MT->chrm->chr
3) The TwoBit …
> Fix for CRAM regularizing failing

- src/JBrowse/Store/SeqFeature/GFF3Tabix.js
This adds a set of defaults for dontRedispatch that corresponds to common elements, chromosome and region, that commonly trigger redispatching that doesn't really make sense.
I think this is a sensible default. It was previously argued to not use this. Note that overriding this variable would have to re-include "chromosome,region,..." if something were to be added which doesn't seem that bad.
I can update docs if this change is suitable
> Add dontRedispatch defaults for GFF3Tabix

- plugins/NeatHTMLFeatures/js/View/Track/NeatFeatures.js
- src/JBrowse/View/Track/HTMLFeatures.js
2 small fixes to avoid error messages when there are too many features to display them all (maximum height reached).
In this case, renderFeature returns null, and we need to check this bfore trying to insertIntrons or appendChild
> NeatHTMLFeatures: fix error when too many features to display

- .travis.yml
- docs/site/global_options.md
- release-notes.md
- src/JBrowse/GenomeView.js
This PR addresses a possible long standing need to allow scroll wheel events to bubble
Here is an example page that uses jbrowse in an iframe embedding
```
<html>
<head>
<body>
<div style="width: 100%; height:100px; background: grey">
<h1>MyWebSite header</h1>
<p>Main menu, about, help, etc</p>
</div>
<iframe id="jbrowse_iframe" width="100%" height="800px" src="index.html"></iframe>
<div style="width: 100%; height:200px; background: grey">
<h1>MyWebSite footer</h1>
<p>(c) 1999</p>
</div>
</body>
</html>
```
If you look at this page without this PR added, any vertical scrolling inside the jbrowse iframe (or div, if it was embedded as a div) would not work, because jbrowse manually stops it. <Edit: Actually not anywhere in the jbrowse iframe, just in the GenomeView panel>
This PR proposes …
> Allow scroll wheel to bubble if no scrolling happened

- package.json
- src/JBrowse/ConfigAdaptor/JB_json_v1.js
- yarn.lock
I can see from some metrics that the objectFingerprint in @scottcain's code is taking a long time. I thought maybe an off-the-shelf version from NPM could speed up
I tested with electron remotely loading his codebase and it was way faster indeed
> Use object-hash package from npm instead of objectFingerprint

- src/JBrowse/Store/Names/Hash.js
This adds a check that the meta data is ready before interpreting the lower casing argument in the meta.json
Fixes a bug raised by @scottcain
> Wait for the ready signal to fix race condition in name store

- src/JBrowse/Browser.js
Previously, if createNavBox was executed multiple times, the last instance would call thisB.navigateTo on every previous instance.
> Isolate monkey-patched dropDownClass in createNavBox

- package.json
- src/JBrowse/Store/SeqFeature/VCFTabix.js
- tests/js_tests/spec/GFF3Tabix.spec.js
- yarn.lock
The VCFFeature apparently never used full line hash so it wasn't making a best effort to de-duplicate features
Nevertheless, now it doesn't need to hash the whole line it can use the fileOffset based IDs since tabix 1.3.2
> Make VCFFeatures use fileOffset based feature IDs

- src/JBrowse/View/Track/_ExportMixin.js
The lang.clone on the highlightedRegion object tries to clone the track reference that it has and that results in error described in #1488 
This just grabs a couple required things from the highlightedRegion object
> Fix clone object

- src/JBrowse/Model/XHRBlob.js
Check for a response.ok before returning results, addressing #1490
> Fix errors for response.ok

- src/JBrowse/View/FeatureGlyph/_FeatureLabelMixin.js
- src/JBrowse/View/Track/CanvasFeatures.js
This enables custom mouseovers to be evaluated when there is no feature label that could be calculated via the default logic for calculating the feature label, e.g. there is no feature name or ID
CC @scottcain
> Allow initializing the popup text with a predefined result

- src/JBrowse/GenomeView.js
If browser tab is deactivated while holding shift, shift keyup wasn't handled
> Release shiftMouse if user switches browser tabs with ctrl+shift+tab

- src/JBrowse/Store/SeqFeature/BAM.js
- src/JBrowse/View/FeatureGlyph/AlignmentColoring.js
This is a special case handling to fix the bug in #1484 but it is slightly awkward, not sure if there is a better way to do this.
> Fix usage of TS vs ts

- docs/site/plugins.md
Added a little bit of formatting to increase the readability of the Example plugin directory contents file list.
Before:
After:
> Better formatting of example plugin directory

- docs/site/url_strings.md
This PR adds some text to clarify the acceptable input values to the `highlight` url parameter. The parameter only accepts inputs in the `chr:start..end` format. However, the text of the previous doc could be misinterpreted to mean that it supported all formats of the `loc` parameter.
> Clarified the highlight parameter input format.

- src/JBrowse/View/FileDialog/TrackList.js
This fixes the ability to use locally opened tracks in a combination track, since storeClass is snooped upon.
> Fix ability to use locally opened tracks in combination tracks

- package.json
- yarn.lock
This adds the possible TextDecoder speedup for jbrowse that was added to @gmod/tabix recently
> Bump @gmod/tabix for textdecoder speedup

- build/dojo-loader-config.js
- package.json
- src/JBrowse/Model/BGZip/BGZBlob.js
- src/JBrowse/Store/SeqFeature/BigWig/RequestWorker.js
- src/JBrowse/Util/arrayCopy.js
- src/JBrowse/Util/jszlib.js
- yarn.lock
This moves jszlib into the codebase to try to potentially help with https://github.com/GMOD/jbrowse/issues/1555
The alternative is publishing the module on npm but it's probably easier to host in our codebase. My reasoning is that more modern solutions exist on npm so it's better to not publish the jszlib ourselves, and it's a bit tough to swap in a more modern solution like pako (doesn't directly slot in...tried this...incompatible with jdataview possibly but didn't look too closely)
> Move jszlib dependency to util directory

- website/siteConfig.js
Possible fix for https://github.com/GMOD/jbrowse-components/issues/2036
Looks like this
> Update jbrowse 1 website header to refer to jbrowse 2
