GMOD/jbrowse

plugins/SVGLollipopTrack/SVGFeatures.js

Revert "fixed some small bugs in SVGFeatures"  wrong code.

---

.gitignore
plugins/NeatHTMLFeatures/README.md
plugins/NeatHTMLFeatures/js/main.js

@enuggetry   This adds a global option for removing linear gradients that defaults to on.  I added it to the doc as well.  Should just work.

Fix plugin option

---

plugins/NeatHTMLFeatures/js/main.js

@enuggetry  I think that this fixes #743.  
I think that somebody already fixed #755 as I can't seem to reproduce it and it was pretty easy to do before.

fixes #743

---

src/JBrowse/Browser.js

Allow loading a Name store from a plugin

---

src/JBrowse/ConfigAdaptor/JB_json_v1.js
src/JBrowse/Store/SeqFeature/SequenceChunks.js

xref https://www.sitepen.com/blog/2014/01/15/faq-cors-with-dojo/

Allow sequence to be requested despite CORS

---

.travis.yml
setup.sh

Replaces #827.  
@cmdcolin    / @enuggetry   Can you review this? 
I think that @keiranmraine  changes were correct (apologies for not checking better myself).
I'm going to double-check the legacy part, but the default install is correct.

fixed legacy install

---

release-notes.txt

Update release notes for PR #945

---

bin/add-bw-track.pl

Useful for automatisation in the case where there are lots of BW files to add.

add category argument in add-bw-track.pl

---

.gitignore
.travis.yml
README.md
build/Makefile
build/insert_tag_version_into_package_jsons.pl
release-notes.txt
tests/selenium_tests/travis_wrapper.sh

Also runs selenium tests against the minified JBrowse release, instead of the source code, so that we test the (rather untrustworthy) minification.
Fixes #822

gave travis the ability to create github releases and upload built zip files to them when tagged

---

.gitignore
.travis.yml
build/set_package_versions.pl
package.json
src/JBrowse/package.json
tests/selenium_tests/travis_wrapper.sh

fill in our package.json some more

add npm deployment to @gmod/jbrowse to travis

---

sample_data/json/modencode/trackList.json

The wiggle tracks on modencode sample data were broken, so this just updates them all to be bigwig tracks

Update to bigwig for modencode tracks

---

css/menubar.scss
src/JBrowse/Browser.js

Fix some of the padding on the top menu popup menu items

Fix spacing in dijitPopupMenus

---

bin/add-bw-track.pl

fix https://github.com/GMOD/jbrowse/issues/1063

fix error in --config option in add-bw-track.pl 

---

release-notes.md
src/JBrowse/Store/SeqFeature/BAM/File.js
src/JBrowse/Store/SeqFeature/BAM/LazyFeature.js

should have thought of this 6 years ago

make BAM feature IDs truly unique. 

---

src/JBrowse/View/GranularRectLayout.js

rewrite GranularRectLayout to be more memory efficient

---

.github/issue_template.md
.github/pull_request_template.md

This adds a simple template for PR and issues on GitHub with some instructions for users

Add templates for PR and issues

---

plugins/NeatHTMLFeatures/js/View/Track/NeatFeatures.js

NeatHTMLFeature: properly display introns when they are already present in gff

---

bin/ucsc-to-json.pl

Fixes https://github.com/GMOD/jbrowse/issues/1345

fix the wrong strand on subfeatures

---

plugins/NeatHTMLFeatures/js/View/Track/NeatFeatures.js

Necessary for fix on this PR: https://github.com/GMOD/Apollo/pull/2186 and to fix this issue: https://github.com/GMOD/Apollo/issues/2149 so we don't draw an intron where it should not.
Please base your pull request based on the "dev" branch of JBrowse
The default branch is "master" but this contains the last stable release, and new pull requests should be based off of "dev"
Then set the base branch to "dev" on GitHub also

add support for showing a Shine Dalgarno sequence

---

.travis.yml

This PR makes travis fail if the target branch is master as it should be dev
Expectation is travis will fail

Travis fail branch target

---

src/perl5/Bio/JBrowse/Cmd/IndexNames.pm

According to the definition of BED files (https://genome.ucsc.edu/FAQ/FAQformat.html#format1), the fourth column is the "Name". Therefore I made a patch similar to the VCFTabix format.

Add support to index names in BEDTabix files

---

src/JBrowse/Browser.js
tests/js_tests/spec/RegularizeRefSeqs.spec.js

This adds ability to regularize the string MtDNA to chrm

Regularize MtDNA

---

docs/site/cors.md
src/perl5/GenomeDB.pm

This adds content-range configs to the .htaccess and the docs

Update the htaccess file and cors docs to include Content-Range

---

src/JBrowse/Browser.js

this makes it so that the electron client writes out the storeClass to the refSeqs config in the trackList.json which reduces ambiguity on reloading (which otherwise relies on inferred file extension)
It also checks for .fasta anyways though just so that the "backwards compatibility" of .fasta already having been in the trackList.json is fixed
Fixes #1415

Allow putting a full storeClass in the refSeqs

---

src/JBrowse/Store/SeqFeature/_MismatchesMixin.js
yarn.lock

Fixes #1438 pending release of a new cram-js version https://github.com/GMOD/cram-js/pull/50

Fix hard clipping on CRAM tracks

---

src/JBrowse/Browser.js

Add relativeUrl config for trackMetadata config

---

docs/site/config_html_features.md
docs/site/configuration_file_format.md
docs/site/data_formats.md
docs/site/events.md
docs/site/faq.md
docs/site/mouse_configs.md
docs/site/track_metadata.md

Might add a couple more to this PR, but just fixes some bad formatting in the docs

Fix some typos in the docs

---

src/JBrowse/Browser.js

This should be a full fix for #764.
Please let me know if any improvements are required.

Fix for #764

---

src/JBrowse/Store/SeqFeature/_MismatchesMixin.js

Fix hard clipping display of mismatches

---

website/build.sh
website/core/Footer.js

With anticipation of the JBrowse 2 website is going live, so we will bump index.html to jbrowse1.html, then link to jbrowse1.html from the jbrowse 2 homepage

Move over for jbrowse 2 website going live

---

src/JBrowse/Browser.js
src/JBrowse/View/Track/SNPCoverage.js
src/JBrowse/View/Track/_AlignmentsMixin.js
src/JBrowse/main.js
src/JBrowse/standalone.js
webpack.config.js
yarn.lock

Was looking for the auto-prefixed .jbrowse .base_a, but now it is .base_a...we might be able to restore .jbrowse to it eventually but this fixes the coloring

Restore alignments track coloring after SASS->CSS change
